/*
 * generated by Xtext 2.25.0
 */
package es.unican.istr.lavoisier;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LavoisierStandaloneSetup extends LavoisierStandaloneSetupGenerated {

	public static void doSetup() {
		new LavoisierStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
