/*
 * generated by Xtext 2.25.0
 */
package es.unican.istr.lavoisier;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LavoisierRuntimeModule extends AbstractLavoisierRuntimeModule {
}
