/*
 * generated by Xtext 2.25.0
 */
package es.unican.istr.lavoisier.ide;


/**
 * Use this class to register ide components.
 */
public class LavoisierIdeModule extends AbstractLavoisierIdeModule {
}
