/*
 * generated by Xtext 2.25.0
 */
package es.unican.istr.lavoisier.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LavoisierUiModule extends AbstractLavoisierUiModule {

	public LavoisierUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
