/*
 * generated by Xtext
 */
package es.unican.lavoisier.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LavoisierUiModule extends es.unican.lavoisier.ui.AbstractLavoisierUiModule {
	public LavoisierUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
