/*
 * generated by Xtext
 */
package es.unican.lavoisier;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LavoisierRuntimeModule extends es.unican.lavoisier.AbstractLavoisierRuntimeModule {

}
