/*
 * generated by Xtext
 */
package es.unican.lavoisier;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class LavoisierStandaloneSetup extends LavoisierStandaloneSetupGenerated{

	public static void doSetup() {
		new LavoisierStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

