/*
 * generated by Xtext 2.25.0
 */
package es.unican.istr.lavoisier.tests

import com.google.inject.Inject
import es.unican.istr.lavoisier.lavoisier.Datasets
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(LavoisierInjectorProvider)
class LavoisierParsingTest {
	@Inject
	ParseHelper<Datasets> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
